from enum import Enum

class RecordType(Enum):
    ACCEL ="accel"
    APP ="app"
    AUDIO_FEA ="audio_fea"
    BT ="bt"
    CALENDAR ="calendar"
    CALENDAR_D ="calendar.d"
    CALL_LOG ="call_log"
    CALL_LOG_D ="call_log.d"
    CONTACTS ="contacts"
    CONTACTS_D ="contacts.d"
    EB ="eb"
    GPS ="gps"
    GPSWLAN ="gpswlan"
    GSM ="gsm"
    MEDIA ="media"
    MEDIA_D ="media.d"
    MEDIA_PLAY ="media_play"
    PROCESS ="process"
    SMS ="sms"
    SMS_D ="sms.d"
    STATE ="state"
    SYS ="sys"
    WLAN ="wlan"
